<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Meta-package that references LiteBus semantic mediator and Microsoft DI extension packages.</Description>
        <PackageTags>$(PackageTags);dependency-injection;composition</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Commands.Extensions.Microsoft.DependencyInjection\LiteBus.Commands.Extensions.Microsoft.DependencyInjection.csproj"/>
        <ProjectReference Include="..\LiteBus.Events.Extensions.Microsoft.DependencyInjection\LiteBus.Events.Extensions.Microsoft.DependencyInjection.csproj"/>
        <ProjectReference Include="..\LiteBus.Messaging.Extensions.Microsoft.DependencyInjection\LiteBus.Messaging.Extensions.Microsoft.DependencyInjection.csproj"/>
        <ProjectReference Include="..\LiteBus.Queries.Extensions.Microsoft.DependencyInjection\LiteBus.Queries.Extensions.Microsoft.DependencyInjection.csproj"/>
    </ItemGroup>

</Project>
