<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="RabbitMQ.Client"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Runtime.Abstractions\LiteBus.Runtime.Abstractions.csproj"/>
        <ProjectReference Include="..\LiteBus.Transport.Abstractions\LiteBus.Transport.Abstractions.csproj"/>
        <ProjectReference Include="..\LiteBus.Transport\LiteBus.Transport.csproj"/>
    </ItemGroup>

</Project>
