<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Convenience meta-package that references LiteBus.Extensions.All and every semantic mediator Microsoft DI extension package.</Description>
        <PackageTags>$(PackageTags);dependency-injection;composition</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Extensions.All\LiteBus.Extensions.All.csproj"/>
    </ItemGroup>

</Project>
