<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>LiteBus.Extensions.MicrosoftDependencyInjection</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Extensions.All\LiteBus.Extensions.All.csproj"/>
    </ItemGroup>

</Project>
