<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Commands.Abstractions\LiteBus.Commands.Abstractions.csproj"/>
        <ProjectReference Include="..\LiteBus.Inbox.Abstractions\LiteBus.Inbox.Abstractions.csproj"/>
        <ProjectReference Include="..\LiteBus.Messaging\LiteBus.Messaging.csproj"/>
        <ProjectReference Include="..\LiteBus.Saga\LiteBus.Saga.csproj"/>
    </ItemGroup>

</Project>
