<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Inbox.Abstractions\LiteBus.Inbox.Abstractions.csproj"/>
        <ProjectReference Include="..\LiteBus.Inbox\LiteBus.Inbox.csproj"/>
        <ProjectReference Include="..\LiteBus.Inbox.Dispatch\LiteBus.Inbox.Dispatch.csproj"/>
        <ProjectReference Include="..\LiteBus.Transport.Kafka\LiteBus.Transport.Kafka.csproj"/>
    </ItemGroup>

</Project>
