<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Runtime.Abstractions\LiteBus.Runtime.Abstractions.csproj"/>
    </ItemGroup>

</Project>
