<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\LiteBus.Outbox.Abstractions\LiteBus.Outbox.Abstractions.csproj"/>
        <ProjectReference Include="..\LiteBus.Outbox.Dispatch\LiteBus.Outbox.Dispatch.csproj"/>
        <ProjectReference Include="..\LiteBus.Transport.AzureServiceBus\LiteBus.Transport.AzureServiceBus.csproj"/>
    </ItemGroup>

</Project>
